/set_ftt_logging_service: /set_ftt_logging
/get_ftt_logging_service: /get_ftt_logging
/save_ftt_params_service: /save_ftt_params
params:
  use_tf: true
  map_frame: longcrossw/odom
  robot_frame: longcrossw/base_link_ground
  server_address: localhost:5000
  send_pose_period: 2
  send_map_period: 5
  image_buffer_size: 3
  image_buffer_step: 1.0
topics:
  robot_mode: robot_mode
  gps_fix: /longcrossw/gps_fix
  local_pose: local_pose
  map: /longcrossw/graph_planner_node/global_costmap/costmap
  map_jpeg: map_jpeg
  image: image
  image_compressed: image_compressed